version: "3"

services:
  mogura:
    build:
      context: .
    volumes:
      - .:/usr/src/mogura
    command: bash -c "digdag server -c digdag.properties"
    ports:
      - "65432:65432"
  db:
    image: postgres:11.1
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mogura
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mogura
  storage:
    image: minio/minio:RELEASE.2020-10-03T02-19-42Z
    container_name: storage
    environment:
      MINIO_ACCESS_KEY: mogura
      MINIO_SECRET_KEY: password
    ports:
      - "9000:9000"
    volumes:
      - ./.volumes:/storage
    entrypoint: sh
    command: -c "mkdir -p /storage/mogura & /usr/bin/minio server /storage"