version: "3"
services:
  mogura:
    build:
      context: .
    volumes:
      - .:/usr/src/mogura
    command: bash -c "digdag server -c digdag.properties"
    ports:
      - "65432:65432"
  db:
    image: postgres:11.1
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mogura
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mogura
