name: Plan
on:
  pull_request:
    branches:
    - master
jobs:
  mogura:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker-compose build
    - name: Test
      run: |
        docker-compose run mogura bundle exec rspec
